- arguments: [
  --color, 
  --cpp-simple,
  -XMagicHash,
  -XImportQualifiedPost,
]
- modules:
  - {name: GHC.Exts, as: GHC} 
  - {
    name: GHC.Magic, 
    message: "Import GHC.Exts qualified as Exts instead",
    within: []
  } 
  - {
    name: GHC.Prim, 
    message: "Import GHC.Exts qualified as Exts instead",
    within: []
  } 
- fixity: infix 4 `gt#`
- fixity: infix 4 `ge#`
- fixity: infix 4 `eq#`
- fixity: infix 4 `ne#`
- fixity: infix 4 `lt#`
- fixity: infix 4 `le#`
