name: GHC 9.2.2
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '**.hs'
      - '**.nix'
      - '**.cabal'
jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-10.15
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2.3.4
        name: Checkout
      - uses: cachix/install-nix-action@v12
        name: Install Nix
        with:
          nix_path: nixpkgs=./nix/pkgs.nix
          extra_nix_config: experimental-features = nix-command
      - run: nix-build --attr prim-compat --argstr ghc "ghc922"